### ISSUE TITLE
SyntaxError: 'return' outside function

### ISSUE THREAD

**Issue by ghost** [pythonism/proxy-checker#3]
hello, i'm having this problem with the script:  (i have installed colorama library)

![pythonism](https://user-images.githubusercontent.com/44337096/48664903-3e919880-eaa6-11e8-9c77-3d21113f6a40.PNG)

I'm using python 3.6

any help?

**Comment by mrcat323** [comment]
hey dude, sorry for a long response, I'm really sorry, this package is no longer maintained, **but I'll try my bext to help you** contact me by e-mail as soon possible if you want. *Thanks*

**Comment by mrcat323** [comment]
aaa, I think I got what's the problem, all this errors are because of tabs. The solution is, to replace all tabs with spaces. It have to work

**Comment by mrcat323** [comment]
Hope you fixed it. :smiley_cat:
