### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by auutlol** [pythonism/proxy-checker#7]
hello great tool you made here but sadly it crashed and said "connection reset by peer" why did that happend? my list has 6k proxies so maybe it's too much? :d

**Comment by awtb** [comment]
Hello friend, please send screenshot and your proxy-list, it help me to find a bug, thanks for using our tool!

**Comment by auutlol** [comment]
i sadly lost it :/ but my issue is why will it stop if the connection get's reset? that way i can't check my proxys properly

**Comment by mrcat323** [comment]
@Verknxt do you have any problems with internet connection ?

**Comment by auutlol** [comment]
> @Verknxt do you have any problems with internet connection ?

nope.

**Comment by mrcat323** [comment]
@Verknxt if you have, or found a solution, you can provide it by creating PR
