### ISSUE TITLE
Multi-thread for checking multiple proxies at once

### ISSUE THREAD

**Issue by alexgarciab** [pythonism/proxy-checker#9]
Hi there, would it be possible if you can add multi-threading to the script? Right now, the checking process is slow an it takes ages to test hundreds of proxies. Thanks!

**Comment by ghost** [comment]
[Multiprocessing](https://docs.python.org/3/library/multiprocessing.html?highlight=processing#module-multiprocessing) would be much better than multithreading due to GIL issue

**Comment by ghost** [comment]
Maybe even multiprocessing+asyncio would be perfect solution
